resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 2
        waitDuration: 5
        ignoreException:
          - java.util.NoSuchElementException
    instances:
      hello:
        baseConfig: default
        maxRetryAttempts: 3