resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 2
        waitDuration: 5
        ignoreException:
          - java.util.NoSuchElementException
    instances:
      retry-hello:
        baseConfig: default
        maxRetryAttempts: 3
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10s
    instances:
      circuit-hello:
        baseConfig: default